import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';
import { useFrictionMap } from '@/hooks/useFrictionMap';
import { ArrowRight, Download, Sparkles, Clock, Zap } from 'lucide-react';

interface FrictionMapBuilderProps {
  compact?: boolean;
}

export const FrictionMapBuilder = ({ compact = false }: FrictionMapBuilderProps) => {
  const [problem, setProblem] = useState('');
  const { frictionMap, isGenerating, generateFrictionMap, clearFrictionMap } = useFrictionMap();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (problem.trim()) {
      await generateFrictionMap(problem.trim());
    }
  };

  // Compact mode - Results view
  if (compact && frictionMap) {
    return (
      <div className="space-y-4">
        <div>
          <div className="text-xs font-bold text-muted-foreground mb-2">TIME SAVED</div>
          <div className="flex items-center justify-center gap-4 p-3 bg-mint/10 rounded-lg">
            <div className="text-center">
              <div className="text-lg font-bold">{frictionMap.timeSaved}h</div>
              <div className="text-[10px] text-muted-foreground">per week</div>
            </div>
            <ArrowRight className="h-4 w-4 text-muted-foreground" />
            <div className="text-center">
              <div className="text-lg font-bold">{frictionMap.timeSaved * 52}h</div>
              <div className="text-[10px] text-muted-foreground">per year</div>
            </div>
          </div>
        </div>
        <div>
          <div className="text-xs font-bold text-muted-foreground mb-2">TOP TOOLS</div>
          <div className="space-y-1">
            {frictionMap.toolRecommendations.slice(0, 2).map((tool, i) => (
              <div key={i} className="flex items-start gap-2 text-xs">
                <div className="w-4 h-4 rounded-full bg-mint/20 text-mint flex items-center justify-center text-[10px] font-bold flex-shrink-0 mt-0.5">
                  {i + 1}
                </div>
                <div className="line-clamp-2">{tool}</div>
              </div>
            ))}
          </div>
        </div>
        <Button
          size="sm"
          variant="outline"
          className="w-full"
          onClick={clearFrictionMap}
        >
          Build Another
        </Button>
      </div>
    );
  }

  // Compact mode - Input form
  if (compact) {
    return (
      <form onSubmit={handleSubmit} className="space-y-3">
        <Input
          value={problem}
          onChange={(e) => setProblem(e.target.value)}
          placeholder="e.g., Weekly reports take 5 hours"
          className="text-sm"
          disabled={isGenerating}
        />
        <Button
          type="submit"
          size="sm"
          className="w-full bg-mint text-ink hover:bg-mint/90 font-bold"
          disabled={isGenerating || !problem.trim()}
        >
          {isGenerating ? (
            <>
              <Sparkles className="h-3 w-3 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            'Generate Map'
          )}
        </Button>
      </form>
    );
  }

  // Full mode continues below...

  const handleDownload = () => {
    if (!frictionMap) return;
    
    const text = `
MY AI FRICTION MAP - Generated by Mindmaker

Problem: ${frictionMap.problem}

CURRENT STATE (Manual):
${frictionMap.currentState}

AI-ENABLED STATE:
${frictionMap.aiEnabledState}

TIME SAVED: ${frictionMap.timeSaved} hours per week
ANNUAL SAVINGS: ${frictionMap.timeSaved * 52} hours per year

RECOMMENDED TOOLS:
${frictionMap.toolRecommendations.map((tool, i) => `${i + 1}. ${tool}`).join('\n')}

Generated on ${frictionMap.generatedAt.toLocaleDateString()}
via https://themindmaker.ai
    `.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'friction-map.txt';
    a.click();
  };

  if (frictionMap) {
    return (
      <Card className="p-6 sm:p-8 -mt-4 bg-white dark:bg-gray-900/90 border border-gray-200 dark:border-gray-700 shadow-lg animate-in fade-in duration-500">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-xl font-bold flex items-center gap-2 text-gray-900 dark:text-white">
            <Sparkles className="h-5 w-5 text-mint dark:text-mint" />
            Your AI Friction Map
          </h3>
          <Button variant="ghost" size="sm" onClick={clearFrictionMap} className="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white">
            Build Another
          </Button>
        </div>

        <div className="space-y-6">
          {/* Problem */}
          <div>
            <div className="text-xs font-bold text-gray-500 dark:text-gray-400 mb-2">YOUR PROBLEM</div>
            <div className="text-lg font-semibold text-gray-900 dark:text-white">{frictionMap.problem}</div>
          </div>

          {/* States Comparison */}
          <div className="grid sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-lg bg-gray-50 dark:bg-gray-800/50 border border-gray-200 dark:border-gray-700">
              <div className="text-xs font-bold text-gray-500 dark:text-gray-400 mb-2">CURRENT STATE</div>
              <p className="text-sm text-gray-700 dark:text-gray-300">{frictionMap.currentState}</p>
            </div>
            <div className="p-4 rounded-lg bg-mint/10 dark:bg-mint/20 border border-mint/30 dark:border-mint/40">
              <div className="text-xs font-bold text-mint dark:text-mint mb-2">AI-ENABLED STATE</div>
              <p className="text-sm text-gray-900 dark:text-white">{frictionMap.aiEnabledState}</p>
            </div>
          </div>

          {/* Time Saved */}
          <div className="flex items-center justify-center gap-8 py-4 bg-gray-50 dark:bg-gray-800/30 rounded-lg">
            <div className="text-center">
              <Clock className="h-6 w-6 text-mint mx-auto mb-2" />
              <div className="text-2xl font-bold text-gray-900 dark:text-white">{frictionMap.timeSaved}h</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Saved per week</div>
            </div>
            <ArrowRight className="h-6 w-6 text-gray-400 dark:text-gray-500" />
            <div className="text-center">
              <Zap className="h-6 w-6 text-mint mx-auto mb-2" />
              <div className="text-2xl font-bold text-gray-900 dark:text-white">{frictionMap.timeSaved * 52}h</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Saved per year</div>
            </div>
          </div>

          {/* Tool Recommendations */}
          <div>
            <div className="text-xs font-bold text-gray-500 dark:text-gray-400 mb-3">RECOMMENDED TOOLS</div>
            <div className="space-y-2">
              {frictionMap.toolRecommendations.map((tool, i) => (
                <div key={i} className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
                  <div className="w-6 h-6 rounded-full bg-mint/20 dark:bg-mint/30 text-mint flex items-center justify-center text-xs font-bold">
                    {i + 1}
                  </div>
                  {tool}
                </div>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t">
            <Button onClick={handleDownload} variant="outline" className="flex-1">
              <Download className="h-4 w-4 mr-2" />
              Download Map
            </Button>
            <Button 
              className="flex-1 bg-mint text-ink hover:bg-mint/90"
              onClick={() => window.location.href = '/builder-session'}
            >
              Build 4 More Like This →
            </Button>
          </div>
        </div>
      </Card>
    );
  }

  return (
    <Card className="p-6 sm:p-8 -mt-4 bg-white dark:bg-gray-900/90 backdrop-blur-sm border border-gray-200 dark:border-gray-700 hover:border-mint dark:hover:border-mint transition-colors shadow-lg">
      <div className="mb-4">
        <h3 className="text-xl font-bold mb-2 flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-mint animate-pulse" />
          Build Your AI Friction Map
        </h3>
        <p className="text-sm text-muted-foreground">
          Every leader needs a friction map. Build yours in 60 seconds.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="text-sm font-medium mb-2 block">
            What's your biggest time drain?
          </label>
          <Input
            value={problem}
            onChange={(e) => setProblem(e.target.value)}
            placeholder="e.g., Weekly reports take 5 hours"
            className="text-base"
            disabled={isGenerating}
          />
        </div>

        <Button
          type="submit"
          size="lg"
          className="w-full bg-mint text-ink hover:bg-mint/90 font-bold"
          disabled={isGenerating || !problem.trim()}
        >
          {isGenerating ? (
            <>
              <Sparkles className="h-4 w-4 mr-2 animate-spin" />
              Generating Your Map...
            </>
          ) : (
            <>
              Generate Friction Map
              <ArrowRight className="h-4 w-4 ml-2" />
            </>
          )}
        </Button>
      </form>

      <p className="text-xs text-muted-foreground mt-4 text-center">
        Free • No email required • Instant results
      </p>
    </Card>
  );
};
