import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Slider } from '@/components/ui/slider';
import { Checkbox } from '@/components/ui/checkbox';
import { usePortfolio } from '@/hooks/usePortfolio';
import { TrendingUp, Download, ArrowRight } from 'lucide-react';

interface PortfolioBuilderProps {
  compact?: boolean;
}

export const PortfolioBuilder = ({ compact = false }: PortfolioBuilderProps) => {
  const { tasks, toggleTask, updateTaskHours, getPortfolioData } = usePortfolio();
  const [showResults, setShowResults] = useState(false);
  const portfolioData = getPortfolioData();

  const handleGenerate = () => {
    if (portfolioData.tasks.length > 0) {
      setShowResults(true);
    }
  };

  const handleDownload = () => {
    const text = `
MY AI PORTFOLIO - Generated by Mindmaker

SELECTED TASKS & TIME SAVINGS:
${portfolioData.tasks.map(t => `
${t.name}
- Current: ${t.hoursPerWeek}h/week
- Saved: ${t.potentialSavings}h/week (40%)
- Tools: ${t.aiTools.join(', ')}
`).join('\n')}

TOTAL IMPACT:
- Time Saved: ${portfolioData.totalTimeSaved}h per week
- Annual Hours: ${portfolioData.totalTimeSaved * 52}h
- Estimated Value: $${portfolioData.totalCostSavings.toLocaleString()}/month

IMPLEMENTATION ROADMAP:
${portfolioData.implementationRoadmap.map((step, i) => `${i + 1}. ${step}`).join('\n')}

Generated via https://themindmaker.ai
    `.trim();

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ai-portfolio.txt';
    a.click();
  };

  if (showResults) {
    return (
      <Card className="p-6 sm:p-8 bg-gradient-to-br from-mint/5 to-ink/5 border-2 border-mint">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-xl font-bold flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-mint" />
            Your AI Portfolio
          </h3>
          <Button variant="ghost" size="sm" onClick={() => setShowResults(false)}>
            Edit
          </Button>
        </div>

        <div className="space-y-6">
          {/* Tasks */}
          <div>
            <div className="text-xs font-bold text-muted-foreground mb-3">YOUR AI SYSTEMS</div>
            <div className="space-y-3">
              {portfolioData.tasks.map(task => (
                <div key={task.id} className="p-4 rounded-lg bg-background border">
                    <div className="flex items-start justify-between mb-2">
                      <div className="font-semibold text-sm">{task.name}</div>
                      <div className="text-right">
                        <div className="text-xs text-muted-foreground">Saves</div>
                        <div className="text-lg font-bold text-mint-dark">{task.potentialSavings}h/wk</div>
                    </div>
                  </div>
                    <div className="text-xs text-muted-foreground space-y-1">
                      <div>Current: {task.hoursPerWeek}h/week</div>
                      <div className="flex flex-wrap gap-1 mt-2">
                        {task.aiTools.map((tool, i) => (
                          <span key={i} className="px-2 py-0.5 bg-mint/10 text-mint-dark rounded-full text-xs">
                            {tool}
                          </span>
                        ))}
                      </div>
                    </div>
                </div>
              ))}
            </div>
          </div>

          {/* Total Impact */}
          <div className="grid sm:grid-cols-2 gap-4 p-4 rounded-lg bg-background">
            <div className="text-center">
              <div className="text-3xl font-bold text-mint-dark">{portfolioData.totalTimeSaved}h</div>
              <div className="text-xs text-muted-foreground">Saved per week</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-gold">${(portfolioData.totalCostSavings / 1000).toFixed(0)}K</div>
              <div className="text-xs text-muted-foreground">Value per month</div>
            </div>
          </div>

          {/* Roadmap */}
          <div>
            <div className="text-xs font-bold text-muted-foreground mb-3">IMPLEMENTATION ROADMAP</div>
            <div className="space-y-2">
              {portfolioData.implementationRoadmap.map((step, i) => (
                <div key={i} className="flex items-start gap-3 text-sm">
                  <div className="w-6 h-6 rounded-full bg-mint/20 text-mint-dark flex items-center justify-center text-xs font-bold flex-shrink-0">
                    {i + 1}
                  </div>
                  <div className="pt-0.5">{step}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t">
            <Button onClick={handleDownload} variant="outline" className="flex-1">
              <Download className="h-4 w-4 mr-2" />
              Download Portfolio
            </Button>
            <Button 
              className="flex-1 bg-mint text-ink hover:bg-mint/90"
              onClick={() => window.location.href = '/builder-sprint'}
            >
              Build This Portfolio →
            </Button>
          </div>
        </div>
      </Card>
    );
  }

  return (
    <Card className="p-6 sm:p-8 bg-background/50 backdrop-blur-sm border-2 border-mint/30 hover:border-mint transition-colors">
      <div className="mb-6">
        <h3 className="text-xl font-bold mb-2">Model out your starting points</h3>
        <p className="text-sm text-muted-foreground">
          Select your weekly tasks and see your personalized transformation roadmap
        </p>
      </div>

      <div className="space-y-6">
        {tasks.map(task => (
          <div key={task.id} className="space-y-3 pb-6 border-b last:border-0">
            <div className="flex items-start gap-3">
              <Checkbox
                id={task.id}
                checked={task.selected}
                onCheckedChange={() => toggleTask(task.id)}
                className="mt-1"
              />
              <label htmlFor={task.id} className="flex-1 cursor-pointer">
                <div className="font-semibold text-sm">{task.name}</div>
                <div className="text-xs text-muted-foreground mt-1">
                  Tools: {task.aiTools.slice(0, 2).join(', ')}
                </div>
              </label>
            </div>

            {task.selected && (
              <div className="ml-7 space-y-2 animate-in fade-in slide-in-from-top-2 duration-300">
                <label className="text-xs text-muted-foreground">
                  Hours per week: <span className="font-bold text-foreground">{task.hoursPerWeek}h</span>
                </label>
                <Slider
                  value={[task.hoursPerWeek]}
                  onValueChange={([value]) => updateTaskHours(task.id, value)}
                  min={1}
                  max={20}
                  step={1}
                  className="w-full"
                />
                {task.hoursPerWeek > 0 && (
                  <div className="text-xs text-mint-dark font-semibold">
                    → Could save {task.potentialSavings}h per week
                  </div>
                )}
              </div>
            )}
          </div>
        ))}
      </div>

      <Button
        onClick={handleGenerate}
        size="lg"
        className="w-full mt-6 bg-mint text-ink hover:bg-mint/90 font-bold"
        disabled={portfolioData.tasks.length === 0}
      >
        Generate Portfolio
        <ArrowRight className="h-4 w-4 ml-2" />
      </Button>
    </Card>
  );
};
