// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksyuwacuigshvcyptlhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzeXV3YWN1aWdzaHZjeXB0bGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODMzMDcsImV4cCI6MjA2OTQ1OTMwN30.4yENHSkSoVv-41rvGMf7yJYXM1TJAF_0sUDJRatdre0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});